// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32_WaveShare_2.8

#ifndef MS5837_SENSOR_H
#define MS5837_SENSOR_H

#ifdef __cplusplus
extern "C"
{
#endif

    bool ms5837_sensor_init(void);

    bool ms5837_sensor_loop(void);

    float get_pressure_psi(void);
    float get_pressure_mbar(void);
    float get_temperature_celsius(void);
    float get_temperature_fahrenheit(void);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // MS5837_SENSOR_H
